"""drop_movie_id_fk_from_watch_history

Revision ID: a6864beeba7f
Revises: ea7bdfade436
Create Date: 2026-04-06 06:08:17.483259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6864beeba7f'
down_revision: Union[str, Sequence[str], None] = 'ea7bdfade436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('featured', 'actors',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('movies', 'duration',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('movies', 'rate',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('movies', 'genre',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('movies', 'director',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('movies', 'age',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('movies', 'translator_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('movies', 'season_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('movies', 'episodes_schedule',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index('ix_wh_user_updated', 'watch_history', ['user_id', 'updated_at'], unique=False)
    op.drop_constraint(op.f('watch_history_movie_id_fkey'), 'watch_history', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('watch_history_movie_id_fkey'), 'watch_history', 'movies', ['movie_id'], ['id'])
    op.drop_index('ix_wh_user_updated', table_name='watch_history')
    op.alter_column('movies', 'episodes_schedule',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('movies', 'season_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('movies', 'translator_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('movies', 'age',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('movies', 'director',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('movies', 'genre',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('movies', 'rate',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('movies', 'duration',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.alter_column('featured', 'actors',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
