server {
    listen 80;
    server_name _;

    location / {
        proxy_pass http://torrserve:8090;
        proxy_http_version 1.1;

        add_header Access-Control-Allow-Origin "*" always;
        add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
        add_header Access-Control-Allow-Headers "*" always;
        add_header Access-Control-Expose-Headers "Content-Length, Content-Range, Accept-Ranges" always;

        proxy_hide_header Content-Disposition;

        if ($request_method = OPTIONS) {
            return 204;
        }
    }
}
